module.exports = {
  // USER
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",
  USER_LOCK: "USER_LOCK",
  USER_UNLOCK: "USER_UNLOCK",
  USER_APPROVE: "USER_APPROVE",
  USER_REJECT: "USER_REJECT",
  USER_CHANGE_ROLE: "USER_CHANGE_ROLE",

  // STORE
  STORE_APPROVE: "STORE_APPROVE",
  STORE_REJECT: "STORE_REJECT",
  STORE_PENDING: "STORE_PENDING",
  STORE_UPDATE: "STORE_UPDATE",
  STORE_DELETE: "STORE_DELETE",

  // PRODUCT
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_UPDATE: "PRODUCT_UPDATE",
  PRODUCT_DELETE: "PRODUCT_DELETE",
  PRODUCT_STATUS_CHANGE: "PRODUCT_STATUS_CHANGE",

  // ORDER
  ORDER_CREATE: "ORDER_CREATE",
  ORDER_STATUS_UPDATE: "ORDER_STATUS_UPDATE",
  ORDER_CANCEL: "ORDER_CANCEL",

  // REVIEW
  REVIEW_DELETE: "REVIEW_DELETE",

  // DISPUTE
  DISPUTE_UPDATE: "DISPUTE_UPDATE",
  DISPUTE_CLOSE: "DISPUTE_CLOSE",

  // COUPON
  COUPON_CREATE: "COUPON_CREATE",
  COUPON_UPDATE: "COUPON_UPDATE",
  COUPON_DELETE: "COUPON_DELETE",

  // ADMIN
  ADMIN_CREATE: "ADMIN_CREATE",
  ADMIN_LOGIN: "ADMIN_LOGIN",
  ADMIN_LOGOUT: "ADMIN_LOGOUT",
};